---
abstract: 'Subclass of Log::Dispatch::Email that uses the Email::Sender::Simple module'
author:
  - 'keroyon <keroyon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Email-EmailSender
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Email::MIME: 0
  Email::Sender::Simple: 0
  Email::Sender::Transport::SMTP: 0
  Encode: 0
  Log::Dispatch: 0
  perl: 5.8.8
resources:
  homepage: http://github.com/keroyonn/p5-Log-Dispatch-Email-EmailSender/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/keroyonn/p5-Log-Dispatch-Email-EmailSender.git
version: 0.02
